"""Initial migration

Revision ID: 1b23456d1acd
Revises: 
Create Date: 2023-11-07 13:57:00.090131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b23456d1acd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('focus_x', sa.Integer(), nullable=True),
    sa.Column('focus_y', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(length=20), nullable=False),
    sa.Column('dimension_x', sa.Integer(), nullable=False),
    sa.Column('dimension_y', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('backdrop', 'character', 'handout', 'map', name='imagetype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_hash'), 'images', ['hash'], unique=False)
    op.create_index(op.f('ix_images_name'), 'images', ['name'], unique=False)
    op.create_index(op.f('ix_images_path'), 'images', ['path'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hit_dice', sa.String(length=50), nullable=False),
    sa.Column('ac', sa.Integer(), nullable=False),
    sa.Column('cr', sa.String(length=10), nullable=False),
    sa.Column('initiative_modifier', sa.Integer(), nullable=False),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('is_PC', sa.Boolean(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_tags',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('image_id', 'tag_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('combat_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_PC', sa.Boolean(), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('ac', sa.Integer(), nullable=False),
    sa.Column('initiative', sa.Integer(), nullable=False),
    sa.Column('initiative_modifier', sa.Integer(), nullable=True),
    sa.Column('conditions', sa.String(length=256), nullable=False),
    sa.Column('has_reaction', sa.Boolean(), nullable=False),
    sa.Column('colour', sa.String(length=10), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['combat_id'], ['combat.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participants')
    op.drop_table('sessions')
    op.drop_table('image_tags')
    op.drop_table('entities')
    op.drop_table('tags')
    op.drop_table('messages')
    op.drop_index(op.f('ix_images_path'), table_name='images')
    op.drop_index(op.f('ix_images_name'), table_name='images')
    op.drop_index(op.f('ix_images_hash'), table_name='images')
    op.drop_table('images')
    op.drop_table('combat')
    # ### end Alembic commands ###
