"""hit dice in participants

Revision ID: 2038e5ba6bff
Revises: c8bb185817b1
Create Date: 2023-11-13 09:35:32.581284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2038e5ba6bff'
down_revision: Union[str, None] = 'c8bb185817b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hit_dice', sa.String(length=50), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_column('hit_dice')

    # ### end Alembic commands ###
