"""Collections

Revision ID: 4491524593f7
Revises: 3a5d7ae4cb22
Create Date: 2024-01-12 15:17:20.362008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4491524593f7'
down_revision: Union[str, None] = '3a5d7ae4cb22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections')),
    sa.UniqueConstraint('name', name=op.f('uq_collections_name'))
    )
    op.create_table('image_collections',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_image_collections_collection_id_collections')),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_image_collections_image_id_images')),
    sa.PrimaryKeyConstraint('image_id', 'collection_id', name=op.f('pk_image_collections'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
