"""weight into rolltablerow

Revision ID: 7929d1acd5cd
Revises: 954e8ab3a2b2
Create Date: 2024-02-17 09:02:17.476493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7929d1acd5cd'
down_revision: Union[str, None] = '954e8ab3a2b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rolltable_rows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rolltable_rows', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
