"""initial migration

Revision ID: c8bb185817b1
Revises: 
Create Date: 2023-11-11 15:14:41.148029

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8bb185817b1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "combat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("active_participant_id", sa.Integer(), nullable=True),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_combat")),
    )
    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=256), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("focus_x", sa.Integer(), nullable=True),
        sa.Column("focus_y", sa.Integer(), nullable=True),
        sa.Column("hash", sa.String(length=20), nullable=False),
        sa.Column("dimension_x", sa.Integer(), nullable=False),
        sa.Column("dimension_y", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("backdrop", "character", "handout", "map", name="imagetype"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_images")),
    )
    with op.batch_alter_table("images", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_images_hash"), ["hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_images_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_images_path"), ["path"], unique=False)

    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(length=400), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("tag", name=op.f("uq_tags_tag")),
    )
    op.create_table(
        "entities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("hit_dice", sa.String(length=50), nullable=False),
        sa.Column("ac", sa.Integer(), nullable=False),
        sa.Column("cr", sa.String(length=10), nullable=False),
        sa.Column("initiative_modifier", sa.Integer(), nullable=False),
        sa.Column("data", sa.BLOB(), nullable=True),
        sa.Column("is_PC", sa.Boolean(), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=10), nullable=True),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["image_id"], ["images.id"], name=op.f("fk_entities_image_id_images")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entities")),
    )
    op.create_table(
        "image_tags",
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"], ["images.id"], name=op.f("fk_image_tags_image_id_images")
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], name=op.f("fk_image_tags_tag_id_tags")),
        sa.PrimaryKeyConstraint("image_id", "tag_id", name=op.f("pk_image_tags")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("backdrop_id", sa.Integer(), nullable=True),
        sa.Column("overlay_image_id", sa.Integer(), nullable=True),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.Column("combat_id", sa.Integer(), nullable=True),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["backdrop_id"], ["images.id"], name=op.f("fk_sessions_backdrop_id_images")
        ),
        sa.ForeignKeyConstraint(
            ["combat_id"], ["combat.id"], name=op.f("fk_sessions_combat_id_combat")
        ),
        sa.ForeignKeyConstraint(
            ["message_id"], ["messages.id"], name=op.f("fk_sessions_message_id_messages")
        ),
        sa.ForeignKeyConstraint(
            ["overlay_image_id"], ["images.id"], name=op.f("fk_sessions_overlay_image_id_images")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_table(
        "participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("combat_id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("is_PC", sa.Boolean(), nullable=False),
        sa.Column("damage", sa.Integer(), nullable=False),
        sa.Column("max_hp", sa.Integer(), nullable=False),
        sa.Column("ac", sa.Integer(), nullable=False),
        sa.Column("initiative", sa.Integer(), nullable=True),
        sa.Column("initiative_modifier", sa.Integer(), nullable=False),
        sa.Column("conditions", sa.String(length=256), nullable=False),
        sa.Column("has_reaction", sa.Boolean(), nullable=False),
        sa.Column("colour", sa.String(length=10), nullable=True),
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["combat_id"], ["combat.id"], name=op.f("fk_participants_combat_id_combat")
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entities.id"], name=op.f("fk_participants_entity_id_entities")
        ),
        sa.ForeignKeyConstraint(
            ["image_id"], ["images.id"], name=op.f("fk_participants_image_id_images")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participants")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("participants")
    op.drop_table("sessions")
    op.drop_table("image_tags")
    op.drop_table("entities")
    op.drop_table("tags")
    op.drop_table("messages")
    with op.batch_alter_table("images", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_images_path"))
        batch_op.drop_index(batch_op.f("ix_images_name"))
        batch_op.drop_index(batch_op.f("ix_images_hash"))

    op.drop_table("images")
    op.drop_table("combat")
    # ### end Alembic commands ###
